apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.service_name }}
  template:
    metadata:
      labels:
        service: {{ .Values.service_name }}
    spec:
      serviceAccountName: {{ .Values.service_name }}
      containers:
      - name: {{ .Values.service_name }}-container
        image: {{ .Values.image_name }}:{{ .Values.image_tag }}
        ports:
          - containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          failureThreshold: 2
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 10
        env:
          - name: PORT
            value: {{ .Values.port | quote }}
          - name: ENVIRONMENT
            value: {{ .Values.environment | quote }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}